dist: trusty
sudo: false
language: cpp

addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - g++-9

script:
        - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake .
        - cmake --build . -- -j2
